# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/osx'
begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  app.name = 'carendar-app-launcher'
  app.version = '1.0'
  app.short_version = '0.3'
  app.frameworks += %W[Security]
  app.identifier = 'de.mateus.carendar-app-launcher'
  app.entitlements['com.apple.security.app-sandbox'] = true
  app.copyright = "Copyright Mateus Armando © 2014"
end
